export const RoutePath = {
    ADMIN: 'admin',
    ACCOUNT: 'accounts',
    CATEGORY: 'categories',
    LOGIN : 'login',
    REGISTER : 'register',
    ABOUT : 'about',
    CHECKOUT : 'checkout',
    ORDER : 'order',
    TABLE : 'table',
    CONTACT : 'contact',
    CART : 'cart',
    SEARCH : 'search',
    PAYMENT: 'payments',
    ADMIN_PRODUCT: 'products',
    ADMIN_ADD_PRODUCT: 'product-add',
    ADMIN_TABLE: 'tables',
    ADMIN_TABLE_ORDER: 'tables-order',
    CUSTOMERS: 'customers',
    SIZES: 'sizes',
}